# Generated by Django 6.0.5 on 2026-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_articleview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articleview',
            new_name='content_art_article_f9e4fb_idx',
            old_name='content_view_article_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='articleview',
            new_name='content_art_user_id_d5c28a_idx',
            old_name='content_view_user_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='articleview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
