# Generated by Django 6.0.5 on 2026-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_videoview_session_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videocomment',
            new_name='videos_vide_video_i_947613_idx',
            old_name='videos_vide_video_i_b9d6a8_idx',
        ),
        migrations.RenameIndex(
            model_name='videolike',
            new_name='videos_vide_video_i_01d9d5_idx',
            old_name='videos_vide_video_i_e35f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='videoview',
            new_name='videos_vide_video_i_14e20f_idx',
            old_name='videos_view_video_i_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='videoview',
            new_name='videos_vide_is_reel_56f76f_idx',
            old_name='videos_view_isreel_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='videoview',
            new_name='videos_vide_user_id_e37b9f_idx',
            old_name='videos_view_user_i_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
